EXIT_REASON = [
    "EXCEPTION_OR_NMI",  # 0x0
    "EXTERNAL_INT",  # 0x1
    "TRIPLE_FAULT",  # 0x2
    "INIT_SIGNAL",  # 0x3
    "STARTUP_IPI",  # 0x4
    "IO_SMI",  # 0x5
    "OTHER_SMI",  # 0x6
    "INTERRUPT_WINDOW",  # 0x7
    "NMI_WINDOW",  # 0x8
    "TASK_SWITCH",  # 0x9
    "CPUID",  # 0xA
    "GETSEC",  # 0xB
    "HLT",  # 0xC
    "INVD",  # 0xD
    "INVLPG",  # 0xE
    "RDPMC",  # 0xF
    "RDTSC",  # 0x10
    "RSM",  # 0x11
    "VMCALL",  # 0x12
    "VMCLEAR",  # 0x13
    "VMLAUNCH",  # 0x14
    "VMPTRLD",  # 0x15
    "VMPTRST",  # 0x16
    "VMREAD",  # 0x17
    "VMRESUME",  # 0x18
    "VMWRITE",  # 0x19
    "VMXOFF",  # 0x1A
    "VMXON",  # 0x1B
    "MOV_CR",  # 0x1C
    "MOV_DR",  # 0x1D
    "IO_INSTRUCTION",  # 0x1E
    "RDMSR",  # 0x1F
    "WRMSR",  # 0x20
    "ENTFAIL_GUEST_STATE",  # 0x21
    "ENTFAIL_MSR_LOADING",  # 0x22
    "----UNUSED----",  # 0x23
    "MWAIT",  # 0x24
    "MONITOR_TRAP_FLAG",  # 0x25
    "----UNUSED----",  # 0x26
    "MONITOR",  # 0x27
    "PAUSE",  # 0x28
    "ENTFAIL_MACHINE_CHK",  # 0x29
    "----UNSUED----",  # 0x2A
    "TPR_BELOW_THRESHOLD",  # 0x2B
    "APIC_ACCESS",  # 0x2C
    "VIRTUALIZED_EOI",  # 0x2D
    "ACCESS_GDTR_OR_IDTR",  # 0x2E
    "ACCESS_LDTR_OR_TR",  # 0x2F
    "EPT_VIOLATION",  # 0x30
    "EPT_MISCONFIG",  # 0x31
    "INVEPT",  # 0x32
    "RDTSCP",  # 0x33
    "VMX_PREEMPT_TIMER",  # 0x34
    "INVVPID",  # 0x35
    "WBINVD",  # 0x36
    "XSETBV",  # 0x37
    "APIC_WRITE",  # 0x38
    "RDRAND",  # 0x39
    "INVPCID",  # 0x3A
    "VMFUNC",  # 0x3B
]
